.TH "KGX" "1" "04/15/2020" "kgx 0\&.2\&.1" "GNOME Console"
.SH "NAME"
Console \- Simple user\-friendly terminal emulator for the GNOME desktop
.SH "SYNOPSIS"
.HP \w'\fBkgx\fR\ 'u
\fBkgx\fR [OPTION]
.SH "DESCRIPTION"
.PP
Console is a simple terminal emulator for GNOME that adjusts nicely
to small screen sizes and touch usage\&.
.SH "OPTIONS"
.SS "Help Options"
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Show help options
.RE
.PP
\fB\-\-help\-all\fR
.RS 4
Show all help options
.RE
.PP
\fB\-\-help\-gapplication\fR
.RS 4
Show GApplication options
.RE
.PP
\fB\-\-help\-gtk\fR
.RS 4
Show GTK+ options
.RE
.SS "Application Options"
.PP
\fB\-\-version\fR
.RS 4
Display Console version\&.
.RE
.PP
\fB\-\-about\fR
.RS 4
Display Console author and copyright information\&.
.RE
.PP
\fB\-e\fR, \fB\-\-command\fR
.RS 4
Execute the argument to this option inside the terminal\&.
.RE
.PP
\fB\-\-working\-directory\=DIRNAME\fR
.RS 4
Set the working directory\&.
.RE
.PP
\fB\-\-wait\fR
.RS 4
Wait until the child exits (TODO)\&.
.RE
.PP
\fB\-\-display\=DISPLAY\fR
.RS 4
X display to use\&.
.RE
.SH "AUTHORS"
.PP
\fBArnaud Ferraris\fR <\&arnaud\&.ferraris@gmail\&.com\&>
