name: build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/vanilla-os/pico:main
      volumes:
        - /proc:/proc
        - /:/run/host
      options: --privileged -it

    steps:
    - uses: actions/checkout@v4

    - name: De-bloat stock image
      run: |
        rm -r /run/host/usr/share/dotnet
        rm -r /run/host${{ runner.tool_cache }}

    - name: Install needed packages
      run: |
        DEBIAN_FRONTEND=noninteractive apt update
        DEBIAN_FRONTEND=noninteractive apt install -y \
          dpkg-dev \
          build-essential \
          debhelper-compat \
          dh-sequence-gnome \
          gsettings-desktop-schemas-dev \
          libadwaita-1-dev \
          libglib2.0-dev \
          libgtop2-dev \
          libgtk-4-dev \
          libpcre2-dev \
          libvte-2.91-gtk4-dev

    - name: Build debian package
      run: |
        wget https://github.com/vanilla-os/gnome-console/tarball/main
        mv main ../gnome-console_45~99-orchid-beta.orig.tar.gz
        dpkg-buildpackage --no-sign
        tar cvf ../gnome-console.tar.xz ../*.deb

    - uses: softprops/action-gh-release@v1
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
        tag_name: "continuous"
        prerelease: true
        name: "Continuous Build"
        files: |
          /__w/gnome-console/gnome-console_45~99-orchid-beta-2_amd64.deb
          /__w/gnome-console/gnome-console.tar.xz
